import 'package:climb_labs/app/data/model/location_detail_model.dart';

final Map<String, List<LocationDetailState>> korToEngLocation = {
  '서울': seoulDetailList,
  '부산': busanDetailList,
  '대구': daeguDetailList,
  '인천': incheonDetailList,
  '광주': gwangjuDetailList,
  '대전': daejeonDetailList,
  '울산': ulsanDetailList,
  '세종': [],
  '경기': gyeonggiDetailList,
  '강원': gangwonDetailList,
  '충북': chungbukDetailList,
  '충남': chungnamDetailList,
  '전남': jeonnamDetailList,
  '경북': gyeongbukDetailList,
  '경남': gyeongnamDetailList,
  '제주': jejuDetailList
};
final List<String> locationList = [
  '서울',
  '부산',
  '대구',
  '인천',
  '광주',
  '대전',
  '울산',
  '세종',
  '경기',
  '강원',
  '충북',
  '충남',
  '전남',
  '경북',
  '경남',
  '제주'
];

final List<LocationDetailState> seoulDetailList = [
  LocationDetailState('강남구'),
  LocationDetailState('강동구'),
  LocationDetailState('강북구'),
  LocationDetailState('강서구'),
  LocationDetailState('관악구'),
  LocationDetailState('강진구'),
  LocationDetailState('구로구'),
  LocationDetailState('금천구'),
  LocationDetailState('노원구'),
  LocationDetailState('도봉구'),
  LocationDetailState('동대문구'),
  LocationDetailState('동작구'),
  LocationDetailState('마포구'),
  LocationDetailState('서대문구'),
  LocationDetailState('서초구'),
  LocationDetailState('성동구'),
  LocationDetailState('성북구'),
  LocationDetailState('송파구'),
  LocationDetailState('양천구'),
  LocationDetailState('영등포구'),
  LocationDetailState('용산구'),
  LocationDetailState('은평구'),
  LocationDetailState('종로구'),
  LocationDetailState('중구'),
  LocationDetailState('중량구'),
];
final List<LocationDetailState> busanDetailList = [
  LocationDetailState('강서구'),
  LocationDetailState('금정구'),
  LocationDetailState('남구'),
  LocationDetailState('동구'),
  LocationDetailState('동래구'),
  LocationDetailState('부산진구'),
  LocationDetailState('북구'),
  LocationDetailState('사상구'),
  LocationDetailState('사하구'),
  LocationDetailState('서구'),
  LocationDetailState('수영구'),
  LocationDetailState('연제구'),
  LocationDetailState('영도구'),
  LocationDetailState('중구'),
  LocationDetailState('해운대구'),
  LocationDetailState('기장군')
];
final List<LocationDetailState> daeguDetailList = [
  LocationDetailState('남구'),
  LocationDetailState('달서구'),
  LocationDetailState('동구'),
  LocationDetailState('북구'),
  LocationDetailState('서구'),
  LocationDetailState('수성구'),
  LocationDetailState('중구'),
  LocationDetailState('달성군')
];
final List<LocationDetailState> incheonDetailList = [
  LocationDetailState('계양구'),
  LocationDetailState('미추홀구'),
  LocationDetailState('남동구'),
  LocationDetailState('동구'),
  LocationDetailState('부평구'),
  LocationDetailState('서구'),
  LocationDetailState('연수구'),
  LocationDetailState('중구'),
  LocationDetailState('강화군'),
  LocationDetailState('옹진군')
];
final List<LocationDetailState> gwangjuDetailList = [
  LocationDetailState('광산구'),
  LocationDetailState('남구'),
  LocationDetailState('동구'),
  LocationDetailState('북구'),
  LocationDetailState('서구')
];
final List<LocationDetailState> daejeonDetailList = [
  LocationDetailState('대덕구'),
  LocationDetailState('동구'),
  LocationDetailState('서구'),
  LocationDetailState('유성구'),
  LocationDetailState('중구')
];
final List<LocationDetailState> ulsanDetailList = [
  LocationDetailState('남구'),
  LocationDetailState('동구'),
  LocationDetailState('북구'),
  LocationDetailState('중구'),
  LocationDetailState('울주군')
];
final List<LocationDetailState> gyeonggiDetailList = [
  LocationDetailState('수원시'),
  LocationDetailState('고양시'),
  LocationDetailState('성남시'),
  LocationDetailState('용인시'),
  LocationDetailState('부천시'),
  LocationDetailState('안산시'),
  LocationDetailState('남양주시'),
  LocationDetailState('안양시'),
  LocationDetailState('화성시'),
  LocationDetailState('남양주시'),
  LocationDetailState('안양시'),
  LocationDetailState('화성시'),
  LocationDetailState('평택시'),
  LocationDetailState('의정부시'),
  LocationDetailState('시흥시'),
  LocationDetailState('파주시'),
  LocationDetailState('김포시'),
  LocationDetailState('광명시'),
  LocationDetailState('광주시'),
  LocationDetailState('군포시'),
  LocationDetailState('오산시'),
  LocationDetailState('이천시'),
  LocationDetailState('양주시'),
  LocationDetailState('안성시'),
  LocationDetailState('구리시'),
  LocationDetailState('포천시'),
  LocationDetailState('의왕시'),
  LocationDetailState('하남시'),
  LocationDetailState('여주시'),
  LocationDetailState('양평군'),
  LocationDetailState('동두천시'),
  LocationDetailState('과천시'),
  LocationDetailState('가평군'),
  LocationDetailState('연천군'),
];

final List<LocationDetailState> gangwonDetailList = [
  LocationDetailState('강릉시'),
  LocationDetailState('동해시'),
  LocationDetailState('삼척시'),
  LocationDetailState('속초시'),
  LocationDetailState('원주시'),
  LocationDetailState('춘천시'),
  LocationDetailState('태백시'),
  LocationDetailState('고성군'),
  LocationDetailState('양구군'),
  LocationDetailState('양양군'),
  LocationDetailState('영월군'),
  LocationDetailState('인제군'),
  LocationDetailState('정선군'),
  LocationDetailState('철원군'),
  LocationDetailState('평창구'),
  LocationDetailState('홍천군'),
  LocationDetailState('화천군'),
  LocationDetailState('횡성군'),
];
final List<LocationDetailState> chungbukDetailList = [
  LocationDetailState('제천시'),
  LocationDetailState('청주시'),
  LocationDetailState('충주시'),
  LocationDetailState('괴산군'),
  LocationDetailState('단양군'),
  LocationDetailState('보은군'),
  LocationDetailState('영동군'),
  LocationDetailState('옥천군'),
  LocationDetailState('음성군'),
  LocationDetailState('진천군'),
  LocationDetailState('증평군'),
  LocationDetailState('청원군'),
];
final List<LocationDetailState> chungnamDetailList = [
  LocationDetailState('공주시'),
  LocationDetailState('논산시'),
  LocationDetailState('보령시'),
  LocationDetailState('서산시'),
  LocationDetailState('아산시'),
  LocationDetailState('천안시'),
  LocationDetailState('금산군'),
  LocationDetailState('당진시'),
  LocationDetailState('부여군'),
  LocationDetailState('서천군'),
  LocationDetailState('연기군'),
  LocationDetailState('예산군'),
  LocationDetailState('청양군'),
  LocationDetailState('태안군'),
  LocationDetailState('홍성군')
];

final List<LocationDetailState> jeonbukDetailList = [
  LocationDetailState('군산시'),
  LocationDetailState('김제시'),
  LocationDetailState('남원시'),
  LocationDetailState('익산시'),
  LocationDetailState('전주시'),
  LocationDetailState('정읍시'),
  LocationDetailState('고창군'),
  LocationDetailState('무주군'),
  LocationDetailState('부안군'),
  LocationDetailState('순창군'),
  LocationDetailState('완주군'),
  LocationDetailState('임실군'),
  LocationDetailState('장수군'),
  LocationDetailState('진안군')
];

final List<LocationDetailState> jeonnamDetailList = [
  LocationDetailState('광양시'),
  LocationDetailState('나주시'),
  LocationDetailState('목포시'),
  LocationDetailState('순천시'),
  LocationDetailState('여수시'),
  LocationDetailState('강진군'),
  LocationDetailState('고흥군'),
  LocationDetailState('곡성군'),
  LocationDetailState('구례군'),
  LocationDetailState('당양군'),
  LocationDetailState('무안군'),
  LocationDetailState('보성군'),
  LocationDetailState('신안군'),
  LocationDetailState('영광군'),
  LocationDetailState('영암군'),
  LocationDetailState('완도군'),
  LocationDetailState('장성군'),
  LocationDetailState('장흥군'),
  LocationDetailState('진도군'),
  LocationDetailState('함평군'),
  LocationDetailState('해남군'),
  LocationDetailState('화순군')
];

final List<LocationDetailState> gyeongbukDetailList = [
  LocationDetailState('경산시'),
  LocationDetailState('경주시'),
  LocationDetailState('구미시'),
  LocationDetailState('김천시'),
  LocationDetailState('문경시'),
  LocationDetailState('상주시'),
  LocationDetailState('안동시'),
  LocationDetailState('영주시'),
  LocationDetailState('영천시'),
  LocationDetailState('포항시'),
  LocationDetailState('고령군'),
  LocationDetailState('군위군'),
  LocationDetailState('봉화군'),
  LocationDetailState('성주군'),
  LocationDetailState('영덕군'),
  LocationDetailState('영양군'),
  LocationDetailState('예천군'),
  LocationDetailState('울릉군'),
  LocationDetailState('울진군'),
  LocationDetailState('의성군'),
  LocationDetailState('청도군'),
  LocationDetailState('청송군'),
  LocationDetailState('칠곡군')
];

final List<LocationDetailState> gyeongnamDetailList = [
  LocationDetailState('거제시'),
  LocationDetailState('김해시'),
  LocationDetailState('밀양시'),
  LocationDetailState('사천시'),
  LocationDetailState('양산시'),
  LocationDetailState('진주시'),
  LocationDetailState('창원시'),
  LocationDetailState('통영시'),
  LocationDetailState('거창군'),
  LocationDetailState('고성군'),
  LocationDetailState('남해군'),
  LocationDetailState('산청군'),
  LocationDetailState('의령군'),
  LocationDetailState('창녕군'),
  LocationDetailState('하동군'),
  LocationDetailState('함안군'),
  LocationDetailState('함양군'),
  LocationDetailState('합천군')
];

final List<LocationDetailState> jejuDetailList = [
  LocationDetailState('서귀포시'),
  LocationDetailState('제주시')
];
