import 'package:climb_labs/app/data/model/location_detail_model.dart';

final Map<String, List<LocationDetail>> korToEngLocation = {
  '서울': seoulDetailList,
  '부산': busanDetailList,
  '대구': daeguDetailList,
  '인천': incheonDetailList,
  '광주': gwangjuDetailList,
  '대전': daejeonDetailList,
  '울산': ulsanDetailList,
  '세종': [],
  '경기': gyeonggiDetailList,
  '강원': gangwonDetailList,
  '충북': chungbukDetailList,
  '충남': chungnamDetailList,
  '전남': jeonnamDetailList,
  '경북': gyeongbukDetailList,
  '경남': gyeongnamDetailList,
  '제주': jejuDetailList
};
final List<String> locationList = [
  '서울',
  '부산',
  '대구',
  '인천',
  '광주',
  '대전',
  '울산',
  '세종',
  '경기',
  '강원',
  '충북',
  '충남',
  '전남',
  '경북',
  '경남',
  '제주'
];

final List<LocationDetail> seoulDetailList = [
  LocationDetail('강남구'),
  LocationDetail('강동구'),
  LocationDetail('강북구'),
  LocationDetail('강서구'),
  LocationDetail('관악구'),
  LocationDetail('강진구'),
  LocationDetail('구로구'),
  LocationDetail('금천구'),
  LocationDetail('노원구'),
  LocationDetail('도봉구'),
  LocationDetail('동대문구'),
  LocationDetail('동작구'),
  LocationDetail('마포구'),
  LocationDetail('서대문구'),
  LocationDetail('서초구'),
  LocationDetail('성동구'),
  LocationDetail('성북구'),
  LocationDetail('송파구'),
  LocationDetail('양천구'),
  LocationDetail('영등포구'),
  LocationDetail('용산구'),
  LocationDetail('은평구'),
  LocationDetail('종로구'),
  LocationDetail('중구'),
  LocationDetail('중량구'),
];
final List<LocationDetail> busanDetailList = [
  LocationDetail('강서구'),
  LocationDetail('금정구'),
  LocationDetail('남구'),
  LocationDetail('동구'),
  LocationDetail('동래구'),
  LocationDetail('부산진구'),
  LocationDetail('북구'),
  LocationDetail('사상구'),
  LocationDetail('사하구'),
  LocationDetail('서구'),
  LocationDetail('수영구'),
  LocationDetail('연제구'),
  LocationDetail('영도구'),
  LocationDetail('중구'),
  LocationDetail('해운대구'),
  LocationDetail('기장군')
];
final List<LocationDetail> daeguDetailList = [
  LocationDetail('남구'),
  LocationDetail('달서구'),
  LocationDetail('동구'),
  LocationDetail('북구'),
  LocationDetail('서구'),
  LocationDetail('수성구'),
  LocationDetail('중구'),
  LocationDetail('달성군')
];
final List<LocationDetail> incheonDetailList = [
  LocationDetail('계양구'),
  LocationDetail('미추홀구'),
  LocationDetail('남동구'),
  LocationDetail('동구'),
  LocationDetail('부평구'),
  LocationDetail('서구'),
  LocationDetail('연수구'),
  LocationDetail('중구'),
  LocationDetail('강화군'),
  LocationDetail('옹진군')
];
final List<LocationDetail> gwangjuDetailList = [
  LocationDetail('광산구'),
  LocationDetail('남구'),
  LocationDetail('동구'),
  LocationDetail('북구'),
  LocationDetail('서구')
];
final List<LocationDetail> daejeonDetailList = [
  LocationDetail('대덕구'),
  LocationDetail('동구'),
  LocationDetail('서구'),
  LocationDetail('유성구'),
  LocationDetail('중구')
];
final List<LocationDetail> ulsanDetailList = [
  LocationDetail('남구'),
  LocationDetail('동구'),
  LocationDetail('북구'),
  LocationDetail('중구'),
  LocationDetail('울주군')
];
final List<LocationDetail> gyeonggiDetailList = [
  LocationDetail('수원시'),
  LocationDetail('고양시'),
  LocationDetail('성남시'),
  LocationDetail('용인시'),
  LocationDetail('부천시'),
  LocationDetail('안산시'),
  LocationDetail('남양주시'),
  LocationDetail('안양시'),
  LocationDetail('화성시'),
  LocationDetail('남양주시'),
  LocationDetail('안양시'),
  LocationDetail('화성시'),
  LocationDetail('평택시'),
  LocationDetail('의정부시'),
  LocationDetail('시흥시'),
  LocationDetail('파주시'),
  LocationDetail('김포시'),
  LocationDetail('광명시'),
  LocationDetail('광주시'),
  LocationDetail('군포시'),
  LocationDetail('오산시'),
  LocationDetail('이천시'),
  LocationDetail('양주시'),
  LocationDetail('안성시'),
  LocationDetail('구리시'),
  LocationDetail('포천시'),
  LocationDetail('의왕시'),
  LocationDetail('하남시'),
  LocationDetail('여주시'),
  LocationDetail('양평군'),
  LocationDetail('동두천시'),
  LocationDetail('과천시'),
  LocationDetail('가평군'),
  LocationDetail('연천군'),
];

final List<LocationDetail> gangwonDetailList = [
  LocationDetail('강릉시'),
  LocationDetail('동해시'),
  LocationDetail('삼척시'),
  LocationDetail('속초시'),
  LocationDetail('원주시'),
  LocationDetail('춘천시'),
  LocationDetail('태백시'),
  LocationDetail('고성군'),
  LocationDetail('양구군'),
  LocationDetail('양양군'),
  LocationDetail('영월군'),
  LocationDetail('인제군'),
  LocationDetail('정선군'),
  LocationDetail('철원군'),
  LocationDetail('평창구'),
  LocationDetail('홍천군'),
  LocationDetail('화천군'),
  LocationDetail('횡성군'),
];
final List<LocationDetail> chungbukDetailList = [
  LocationDetail('제천시'),
  LocationDetail('청주시'),
  LocationDetail('충주시'),
  LocationDetail('괴산군'),
  LocationDetail('단양군'),
  LocationDetail('보은군'),
  LocationDetail('영동군'),
  LocationDetail('옥천군'),
  LocationDetail('음성군'),
  LocationDetail('진천군'),
  LocationDetail('증평군'),
  LocationDetail('청원군'),
];
final List<LocationDetail> chungnamDetailList = [
  LocationDetail('공주시'),
  LocationDetail('논산시'),
  LocationDetail('보령시'),
  LocationDetail('서산시'),
  LocationDetail('아산시'),
  LocationDetail('천안시'),
  LocationDetail('금산군'),
  LocationDetail('당진시'),
  LocationDetail('부여군'),
  LocationDetail('서천군'),
  LocationDetail('연기군'),
  LocationDetail('예산군'),
  LocationDetail('청양군'),
  LocationDetail('태안군'),
  LocationDetail('홍성군')
];

final List<LocationDetail> jeonbukDetailList = [
  LocationDetail('군산시'),
  LocationDetail('김제시'),
  LocationDetail('남원시'),
  LocationDetail('익산시'),
  LocationDetail('전주시'),
  LocationDetail('정읍시'),
  LocationDetail('고창군'),
  LocationDetail('무주군'),
  LocationDetail('부안군'),
  LocationDetail('순창군'),
  LocationDetail('완주군'),
  LocationDetail('임실군'),
  LocationDetail('장수군'),
  LocationDetail('진안군')
];

final List<LocationDetail> jeonnamDetailList = [
  LocationDetail('광양시'),
  LocationDetail('나주시'),
  LocationDetail('목포시'),
  LocationDetail('순천시'),
  LocationDetail('여수시'),
  LocationDetail('강진군'),
  LocationDetail('고흥군'),
  LocationDetail('곡성군'),
  LocationDetail('구례군'),
  LocationDetail('당양군'),
  LocationDetail('무안군'),
  LocationDetail('보성군'),
  LocationDetail('신안군'),
  LocationDetail('영광군'),
  LocationDetail('영암군'),
  LocationDetail('완도군'),
  LocationDetail('장성군'),
  LocationDetail('장흥군'),
  LocationDetail('진도군'),
  LocationDetail('함평군'),
  LocationDetail('해남군'),
  LocationDetail('화순군')
];

final List<LocationDetail> gyeongbukDetailList = [
  LocationDetail('경산시'),
  LocationDetail('경주시'),
  LocationDetail('구미시'),
  LocationDetail('김천시'),
  LocationDetail('문경시'),
  LocationDetail('상주시'),
  LocationDetail('안동시'),
  LocationDetail('영주시'),
  LocationDetail('영천시'),
  LocationDetail('포항시'),
  LocationDetail('고령군'),
  LocationDetail('군위군'),
  LocationDetail('봉화군'),
  LocationDetail('성주군'),
  LocationDetail('영덕군'),
  LocationDetail('영양군'),
  LocationDetail('예천군'),
  LocationDetail('울릉군'),
  LocationDetail('울진군'),
  LocationDetail('의성군'),
  LocationDetail('청도군'),
  LocationDetail('청송군'),
  LocationDetail('칠곡군')
];

final List<LocationDetail> gyeongnamDetailList = [
  LocationDetail('거제시'),
  LocationDetail('김해시'),
  LocationDetail('밀양시'),
  LocationDetail('사천시'),
  LocationDetail('양산시'),
  LocationDetail('진주시'),
  LocationDetail('창원시'),
  LocationDetail('통영시'),
  LocationDetail('거창군'),
  LocationDetail('고성군'),
  LocationDetail('남해군'),
  LocationDetail('산청군'),
  LocationDetail('의령군'),
  LocationDetail('창녕군'),
  LocationDetail('하동군'),
  LocationDetail('함안군'),
  LocationDetail('함양군'),
  LocationDetail('합천군')
];

final List<LocationDetail> jejuDetailList = [
  LocationDetail('서귀포시'),
  LocationDetail('제주시')
];
